name: Discord Notification

on:
    push:
        branches:
            - main
        paths:
            - 'blog/**'
            - 'public/**'
    pull_request:
        types: [closed]
        paths:
            - 'blog/**'
            - 'public/**'

jobs:
    notify:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true || github.event_name == 'push'
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v40
              with:
                  files: |
                      blog/**/*.md
                      public/**/*.html

            - name: Send notification for PR merge
              if: github.event.pull_request.merged == true
              run: |
                  PR_TITLE="${{ github.event.pull_request.title }}"
                  PR_NUMBER="${{ github.event.pull_request.number }}"
                  PR_URL="${{ github.event.pull_request.html_url }}"
                  CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
                  
                  DISCORD_MESSAGE="🎉 **PR #$PR_NUMBER fusionnée**: $PR_TITLE"
                  DISCORD_MESSAGE="$DISCORD_MESSAGE\n📝 [Voir la PR]($PR_URL)"
                  
                  if [ -n "$CHANGED_FILES" ]; then
                    DISCORD_MESSAGE="$DISCORD_MESSAGE\n🔄 Fichiers modifiés:"
                  
                    for file in $CHANGED_FILES; do
                      DISCORD_MESSAGE="$DISCORD_MESSAGE\n- \`$file\`"
                    done
                  fi
                  
                  curl -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
                    -H "Content-Type: application/json" \
                    -d "{\"content\": \"$DISCORD_MESSAGE\", \"username\": \"Gros sac orange\"}"

            - name: Send notification for direct push
              if: github.event_name == 'push'
              run: |
                  COMMIT_MSG="${{ github.event.head_commit.message }}"
                  COMMIT_URL="${{ github.event.head_commit.url }}"
                  CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
                  
                  DISCORD_MESSAGE="📢 **Nouveau commit sur main**: $COMMIT_MSG"
                  DISCORD_MESSAGE="$DISCORD_MESSAGE\n📝 [Voir le commit]($COMMIT_URL)"
                  
                  if [ -n "$CHANGED_FILES" ]; then
                    DISCORD_MESSAGE="$DISCORD_MESSAGE\n🔄 Fichiers modifiés:"
                  
                    for file in $CHANGED_FILES; do
                      DISCORD_MESSAGE="$DISCORD_MESSAGE\n- \`$file\`"
                    done
                  fi
                  
                  curl -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
                    -H "Content-Type: application/json" \
                    -d "{\"content\": \"$DISCORD_MESSAGE\", \"username\": \"Gros sac orange\"}"