name: Generate Article

on:
    workflow_dispatch:
        inputs:
            topic:
                description: 'Sujet de l''article à générer'
                required: true
                type: string
            tags:
                description: 'Tags de l''article (séparés par des virgules)'
                required: false
                type: string
                default: 'ia, technologie'

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Generate article
              run: node scripts/generate-article.js "${{ github.event.inputs.topic }}"
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

            - name: Build site
              run: npm run build